eSchool/app_course/urls.py
from django.urls import path
from . import views

app_name = 'app_course'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('publish/', views.PublishCourse.as_view(), name='publish'),
    path('course_details/<slug:slug>/', views.course_details, name='course_details'),
    path('my_courses/', views.MyCourses.as_view(), name='my_courses'),
    path('question/<pk>/', views.question, name='question'),
]

eSchool/app_login/urls.py
from django.urls import path
from . import views

app_name = 'app_login'

urlpatterns = [
    path('initial/', views.initial_page, name='initial'),
    path('login_teacher/', views.teacher_login, name='login_teacher'),
    path('login_student/', views.student_login, name='login_student'),
    path('sign_up_teacher/', views.teacher_sign_up, name='sign_up_teacher'),
    path('sign_up_student/', views.student_sign_up, name='sign_up_student'),
    path('logout/', views.logout_user, name='logout'),
    path('teacher_profile/', views.teacher_profile, name='profile_teacher'),
    path('student_profile/', views.student_profile, name='profile_student'),
    path('edit_teacher/', views.edit_teacher, name='edit_teacher'),
    path('edit_student/', views.edit_student, name='edit_student'),
]

eSchool/eSchool/urls.py
from django.contrib import admin
from django.urls import path, include
from app_course.views import Home
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('app_login.urls')),
    path('course/', include('app_course.urls')),
    path('', Home.as_view(), name='home'),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eSchool/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <title>{% block title_block %} {% endblock %}</title>
    {% block css_block %} {% endblock %}
</head>

<body>
    <!-- navbar section -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'app_course:home' %}">eSchool</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        @{{user.username}}
                    </a>
                    <div class="dropdown-menu">
                        {% if user.teacher_profile %}
                        <a class="dropdown-item" href="{% url 'app_course:my_courses' %}">My Courses</a>
                        <a class="dropdown-item" href="{% url 'app_login:profile_teacher' %}">Your Profile</a>
                        {% else %}
                        <a class="dropdown-item" href="{% url 'app_login:profile_student' %}">Your Profile</a>
                        {% endif %}
                        <hr>
                        <a class="dropdown-item" href="{% url 'app_login:logout' %}">Logout</a>
                    </div>
                </div>
            </ul>
        </div>
    </nav>

    <!-- body section -->
    
    <div class="container p-5">
        {% block body_block %}

        {% endblock %}
    </div>

</body>

</html>