eSchool/app_course/urls.py
from django.urls import path
from . import views

app_name = 'app_course'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('publish/', views.PublishCourse.as_view(), name='publish'),
    path('course_details/<slug:slug>/', views.course_details, name='course_details'),
    path('my_courses/', views.MyCourses.as_view(), name='my_courses'),
    path('question/<pk>/', views.question, name='question'),
]

eSchool/app_login/urls.py
from django.urls import path
from . import views

app_name = 'app_login'

urlpatterns = [
    path('initial/', views.initial_page, name='initial'),
    path('login_teacher/', views.teacher_login, name='login_teacher'),
    path('login_student/', views.student_login, name='login_student'),
    path('sign_up_teacher/', views.teacher_sign_up, name='sign_up_teacher'),
    path('sign_up_student/', views.student_sign_up, name='sign_up_student'),
    path('logout/', views.logout_user, name='logout'),
    path('teacher_profile/', views.teacher_profile, name='profile_teacher'),
    path('student_profile/', views.student_profile, name='profile_student'),
    path('edit_teacher/', views.edit_teacher, name='edit_teacher'),
    path('edit_student/', views.edit_student, name='edit_student'),
]

eSchool/eSchool/urls.py
from django.contrib import admin
from django.urls import path, include
from app_course.views import Home
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('app_login.urls')),
    path('course/', include('app_course.urls')),
    path('', Home.as_view(), name='home'),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eSchool/app_login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='teacher_profile')
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    email = models.EmailField(blank=True)
    job_title = models.CharField(max_length=50, blank=True)
    subject = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.user.username

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='student_profile')
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    email = models.EmailField(blank=True)
    institution = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.user.username
    

eSchool/app_login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import Teacher, Student

class LoginForm(AuthenticationForm):
    username = forms.CharField(required=True, label="",widget=forms.TextInput(attrs={'placeholder': 'username'}))
    password = forms.CharField(
        required=True,
        label = "",
        widget=forms.PasswordInput(attrs={'placeholder': 'password'})
    )
    class Meta:
        model = User
        fields = ('username', 'password')

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, label="",widget=forms.TextInput(attrs={'placeholder': 'user@example.com'}))
    username = forms.CharField(required=True, label="",widget=forms.TextInput(attrs={'placeholder': 'username'}))
    password1 = forms.CharField(
        required=True,
        label = "",
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )
    password2 = forms.CharField(
        required=True,
        label = "",
        widget=forms.PasswordInput(attrs={'placeholder': 'Re-enter the password'})
    )
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class EditTeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        exclude = ('user', )

class EditStudentForm(forms.ModelForm):
    class Meta:
        model = Student
        exclude = ('user', )

eSchool/app_login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from .models import Teacher, Student
from .forms import LoginForm, SignUpForm, EditStudentForm, EditTeacherForm

# Create your views here.

def initial_page(request):
    return render(request, 'app_login/initial.html', {})

# teacher and student login
def teacher_login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('app_login:profile_teacher'))
    return render(request, 'app_login/login.html', {'teacher': True, 'form': form})

def student_login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('app_login:profile_student'))
    return render(request, 'app_login/login.html', {'form': form})

# sign up part
def teacher_sign_up(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            teacher_profile = Teacher(user=user)
            teacher_profile.save()
            return HttpResponseRedirect(reverse('app_login:login_teacher'))
    return render(request, 'app_login/sign_up.html', {'teacher': True, 'form':form}) 

def student_sign_up(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            student_profile = Student(user=user)
            student_profile.save()
            return HttpResponseRedirect(reverse('app_login:login_student'))
    return render(request, 'app_login/sign_up.html', {'form':form}) 

# logout part
@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('app_login:initial'))

# profile view
@login_required
def teacher_profile(request):
    return render(request, 'app_login/profile.html', {'teacher': True})

@login_required
def student_profile(request):
    return render(request, 'app_login/profile.html', {})

# edit profile

@login_required
def edit_teacher(request):
    current_user = Teacher.objects.get(user=request.user)
    form = EditTeacherForm(instance=current_user)
    if request.method == 'POST':
        form = EditTeacherForm(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = EditTeacherForm(instance=current_user)
            return HttpResponseRedirect(reverse('app_login:profile_teacher'))
    return render(request, 'app_login/edit_profile.html', {'form': form})

@login_required
def edit_student(request):
    current_user = Student.objects.get(user=request.user)
    form = EditStudentForm(instance=current_user)
    if request.method == 'POST':
        form = EditStudentForm(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = EditStudentForm(instance=current_user)
            return HttpResponseRedirect(reverse('app_login:profile_student'))
    return render(request, 'app_login/edit_profile.html', {'form': form})

eSchool/templates/app_login/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Edit profile {% endblock %}
{% block css_block %}

{% endblock %}
{% block body_block %}

<div class='edit-profile'>
    <h5>Edit your profile</h5>
    <form method="POST" enctype="multipart/form-data">
      {{ form|crispy}}
      {% csrf_token %}
      <button type="submit" style="width:100%" class="btn btn-primary">Update</button>
    </form>
  </div>

{% endblock %}

eSchool/templates/app_login/initial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <title>Welcome to eSchool</title>
</head>
<body style="font-family: Verdana, Geneva, Tahoma, sans-serif;">
    <div class="container p-5">
        <div class="row p-5">
            <h1 class="text-center">Welcome to eSchool</h1> <br>
        </div>
        <div class="row p-5">
            <center>
                
                    <p class="text-center">Join as</p> <br>
                    <a href="{% url 'app_login:login_teacher' %}" class="btn btn-info btn-md">Teacher</a> <br>
                    or <br>
                    <a href="{% url 'app_login:login_student' %}" class="btn btn-primary btn-md">Student</a>
                
            </center>
        </div>
    </div>
</body>
</html>

eSchool/templates/app_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block css_block %}
<style>
    .sign_up {
        width: 450px;
        border: 1px solid #ccc;
        padding: 40px;
    }

    .log_in {
        width: 450px;
        padding: 20px;
        border: 1px solid #ccc;
    }
</style>
{% endblock %}

{% block body_block %}
<center>
    <div class='sign_up'>
        {% if teacher %}
        <h5>Log in to your teacher account.</h5>
        {% else %}
        <h5>Log in to your student account.</h5>
        {% endif %}
        <form method="POST">
            {{ form|crispy}}
            {% csrf_token %}
            <button type="submit" style="width:100%" class="btn btn-primary">Login</button>
        </form>
    </div>
    <div class="log_in my-3">
        <p>Don't have an account?
            {% if teacher %} 
            <a href="{% url 'app_login:sign_up_teacher' %}">
            {% else %}
            <a href="{% url 'app_login:sign_up_student' %}">
            {% endif %}
            Sign up</a>
        </p>
    </div>
</center>


{% endblock %}

eSchool/templates/app_login/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title_block %} Profile {% endblock %}
{% block body_block %} 

<h2 class="text-center">Welcome to eSchool</h2>
<div class="row pt-5">
    <div class="col-sm-4">
        <img src="/static/images/unisex_avatar.jpg" width="250px" height="250px" class="rounded-circle" alt="default">
    </div>
    <div class="col-sm-8">
        <br>
        {% if teacher %}
        <h3 class="text-center">Teacher profile</h3>
        <p>
            <strong>Username: </strong>@{{user.username}} <br>
            <strong>Name: </strong>{{user.teacher_profile.first_name}} {{user.teacher_profile.last_name}} <br>
            <strong>Email address: </strong>{{user.teacher_profile.email}} <br>
            <strong>Subject: </strong>{{user.teacher_profile.subject}} <br>
            <p class="text-muted">{{user.teacher_profile.job_title}}</p><br>
            <a href="{% url 'app_login:edit_teacher' %}" class="btn btn-info btn-sm">Edit profile</a>&nbsp;
            <a href="{% url 'app_course:publish' %}" class="btn btn-secondary btn-sm">Publish a course</a>
        </p>
        {% else %}
        <p>
            <strong>Username: </strong>@{{user.username}} <br>
            <strong>Name: </strong>{{user.student_profile.first_name}} {{user.student_profile.last_name}} <br>
            <strong>Email address: </strong>{{user.student_profile.email}} <br>
            <p class="text-muted">{{user.student_profile.institution}}</p><br>
            <a href="{% url 'app_login:edit_student' %}" class="btn btn-info btn-sm">Edit profile</a>
        </p>
        {% endif %}
    </div>
</div><hr>


{% endblock %}

eSchool/templates/app_login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Sign up {% endblock %}
{% block css_block %}
<style>
    .sign_up {
        width: 450px;
        border: 1px solid #ccc;
        padding: 40px;
    }

    .log_in {
        width: 450px;
        padding: 20px;
        border: 1px solid #ccc;
    }
</style>
{% endblock %}

{% block body_block %}
<center>
    <div class='sign_up'>
        {% if teacher %}
        <h5>Sign up for a teacher account.</h5>
        {% else %}
        <h5>Sign up for a student account.</h5>
        {% endif %}
        <form method="POST">
            {{ form|crispy}}
            {% csrf_token %}
            <button type="submit" style="width:100%" class="btn btn-primary">Sign up</button>
        </form>
    </div>
    <div class="log_in my-3">
        <p>Have an account?
            {% if teacher %} 
            <a href="{% url 'app_login:login_teacher' %}">
            {% else %}
            <a href="{% url 'app_login:login_student' %}">
            {% endif %}
            Login here</a>
        </p>
    </div>
</center>


{% endblock %}